/******************************************************************************
*  Generated by PSoC Designer 5.4.3191
******************************************************************************/
#include <m8c.h>
// INT_Pin address and mask defines
#pragma	ioport	INT_Pin_Data_ADDR:	0x0
BYTE			INT_Pin_Data_ADDR;
#pragma	ioport	INT_Pin_DriveMode_0_ADDR:	0x100
BYTE			INT_Pin_DriveMode_0_ADDR;
#pragma	ioport	INT_Pin_DriveMode_1_ADDR:	0x101
BYTE			INT_Pin_DriveMode_1_ADDR;
#pragma	ioport	INT_Pin_DriveMode_2_ADDR:	0x3
BYTE			INT_Pin_DriveMode_2_ADDR;
#pragma	ioport	INT_Pin_GlobalSelect_ADDR:	0x2
BYTE			INT_Pin_GlobalSelect_ADDR;
#pragma	ioport	INT_Pin_IntCtrl_0_ADDR:	0x102
BYTE			INT_Pin_IntCtrl_0_ADDR;
#pragma	ioport	INT_Pin_IntCtrl_1_ADDR:	0x103
BYTE			INT_Pin_IntCtrl_1_ADDR;
#pragma	ioport	INT_Pin_IntEn_ADDR:	0x1
BYTE			INT_Pin_IntEn_ADDR;
#define INT_Pin_MASK 0x4
// RxD address and mask defines
#pragma	ioport	RxD_Data_ADDR:	0x0
BYTE			RxD_Data_ADDR;
#pragma	ioport	RxD_DriveMode_0_ADDR:	0x100
BYTE			RxD_DriveMode_0_ADDR;
#pragma	ioport	RxD_DriveMode_1_ADDR:	0x101
BYTE			RxD_DriveMode_1_ADDR;
#pragma	ioport	RxD_DriveMode_2_ADDR:	0x3
BYTE			RxD_DriveMode_2_ADDR;
#pragma	ioport	RxD_GlobalSelect_ADDR:	0x2
BYTE			RxD_GlobalSelect_ADDR;
#pragma	ioport	RxD_IntCtrl_0_ADDR:	0x102
BYTE			RxD_IntCtrl_0_ADDR;
#pragma	ioport	RxD_IntCtrl_1_ADDR:	0x103
BYTE			RxD_IntCtrl_1_ADDR;
#pragma	ioport	RxD_IntEn_ADDR:	0x1
BYTE			RxD_IntEn_ADDR;
#define RxD_MASK 0x8
// LED address and mask defines
#pragma	ioport	LED_Data_ADDR:	0x0
BYTE			LED_Data_ADDR;
#pragma	ioport	LED_DriveMode_0_ADDR:	0x100
BYTE			LED_DriveMode_0_ADDR;
#pragma	ioport	LED_DriveMode_1_ADDR:	0x101
BYTE			LED_DriveMode_1_ADDR;
#pragma	ioport	LED_DriveMode_2_ADDR:	0x3
BYTE			LED_DriveMode_2_ADDR;
#pragma	ioport	LED_GlobalSelect_ADDR:	0x2
BYTE			LED_GlobalSelect_ADDR;
#pragma	ioport	LED_IntCtrl_0_ADDR:	0x102
BYTE			LED_IntCtrl_0_ADDR;
#pragma	ioport	LED_IntCtrl_1_ADDR:	0x103
BYTE			LED_IntCtrl_1_ADDR;
#pragma	ioport	LED_IntEn_ADDR:	0x1
BYTE			LED_IntEn_ADDR;
#define LED_MASK 0x10
// TxD address and mask defines
#pragma	ioport	TxD_Data_ADDR:	0x0
BYTE			TxD_Data_ADDR;
#pragma	ioport	TxD_DriveMode_0_ADDR:	0x100
BYTE			TxD_DriveMode_0_ADDR;
#pragma	ioport	TxD_DriveMode_1_ADDR:	0x101
BYTE			TxD_DriveMode_1_ADDR;
#pragma	ioport	TxD_DriveMode_2_ADDR:	0x3
BYTE			TxD_DriveMode_2_ADDR;
#pragma	ioport	TxD_GlobalSelect_ADDR:	0x2
BYTE			TxD_GlobalSelect_ADDR;
#pragma	ioport	TxD_IntCtrl_0_ADDR:	0x102
BYTE			TxD_IntCtrl_0_ADDR;
#pragma	ioport	TxD_IntCtrl_1_ADDR:	0x103
BYTE			TxD_IntCtrl_1_ADDR;
#pragma	ioport	TxD_IntEn_ADDR:	0x1
BYTE			TxD_IntEn_ADDR;
#define TxD_MASK 0x20
// I2CHWSDA address and mask defines
#pragma	ioport	I2CHWSDA_Data_ADDR:	0x4
BYTE			I2CHWSDA_Data_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSDA_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSDA_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSDA_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSDA_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSDA_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSDA_IntEn_ADDR:	0x5
BYTE			I2CHWSDA_IntEn_ADDR;
#define I2CHWSDA_MASK 0x1
// I2CHWSCL address and mask defines
#pragma	ioport	I2CHWSCL_Data_ADDR:	0x4
BYTE			I2CHWSCL_Data_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSCL_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSCL_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSCL_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSCL_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSCL_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSCL_IntEn_ADDR:	0x5
BYTE			I2CHWSCL_IntEn_ADDR;
#define I2CHWSCL_MASK 0x2
